# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Build and publish app release conventionally

on:
  workflow_dispatch:
    branches: stable*
    inputs:
      prerelease:
        description: 'Pre-release'
        type: boolean
        required: true
      prereleaseIdentifier:
        description: 'Pre-release identifier'
        required: true
        default: 'rc'
        type: choice
        options:
          - alpha
          - beta
          - rc

env:
  PHP_VERSION: 8.3

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "APP_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@952b14bbc4be87e8458a6ac5926fc655608b1b19 # v6
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          git-user-email: nextcloud-command@users.noreply.github.com
          git-user-name: Nextcloud Command Bot
          skip-git-pull: "true"
          pre-commit: build/pre-commit.js
          release-count: 0
          version-file: "package.json, package-lock.json"
          pre-release: ${{ inputs.prerelease }}
          pre-release-identifier: ${{ inputs.prereleaseIdentifier }}
      - name: Debug changelog outputs
        run: |
          echo "skipped:         ${{ steps.changelog.outputs.skipped }}"
          echo "tag:             ${{ steps.changelog.outputs.tag }}"
          echo "version:         ${{ steps.changelog.outputs.version }}"
          echo "clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}"
          echo "changelog:       ${{ steps.changelog.outputs.changelog }}"
 
